### ISSUE TITLE
GM: add Switchboard oracles

### ISSUE THREAD

**Issue by y2kappa** [hubbleprotocol/scope#26]
v2: https://switchboard.xyz/explorer/3/9LNYQZLJG5DAyeACCTzBFG6H3sDhehP5xtYLdhrZtQkA
v1: [add switchboard stSOL - SOL](https://switchboard.xyz/explorer/1/2CpB8n1hntXDCQ3E7wEARZH8S8mrtdpZhG2FdYZs8NoU)

https://github.com/solendprotocol/solana-program-library/search?q=switchboard

**Comment by gmmour1** [comment]
@y2kappa request:
https://switchboard.xyz/explorer/1/37NFcKPTgqUVx3gwTQ4c2Q94oJWk2xZy3NQUXtDixReb

**Comment by oeble** [comment]
support for switchboard is done.
